
#include <string.h>
#include "terminal_xml.h"

UIView *terminal_xml_build(SettingsXmlIds *ids)
{
    if (ids) memset(ids, 0, sizeof(*ids));
    const int32_t screen_w = lv_disp_get_hor_res(NULL);
    const int32_t screen_h = lv_disp_get_ver_res(NULL);

    UIView *page = UIView_create(NULL);
    UIView_set_background_color(page, 0xF7F7FA);
    UIView_set_frame(page, 0, 0, screen_w, screen_h);
UIView *_v0 = UIView_create((UIView *)page);
UIView_set_background_color((UIView *)_v0, 0xF7F7FA);
UIView_set_frame((UIView *)_v0, 0, 0, (screen_w) * 100 / 100, (screen_h) * 100 / 100);
UIButton *back = UIButton_create((UIView *)_v0);
UIButton_set_text(back, LV_SYMBOL_LEFT " Back");
UIButton_set_title_color((UIButton *)back, 0x1F2328);
UIView_set_background_color((UIView *)back, 0xE9EBEF);
lv_obj_set_style_bg_color(UIView_native((UIView *)back), lv_color_hex(0xD3D7DD), LV_PART_MAIN | LV_STATE_PRESSED);
UIView_set_corner_radius((UIView *)back, 16);
UIView_set_frame((UIView *)back, 20, 56, 130, 44);
UILabel *appTitle_1 = UILabel_create((UIView *)_v0);
UILabel_set_text(appTitle_1, "Terminal");
UILabel_set_color((UILabel *)appTitle_1, 0x1F2328);
UILabel_set_font((UILabel *)appTitle_1, &lv_font_montserrat_28);
UILabel_set_alignment((UILabel *)appTitle_1, 1);
UIView_set_frame((UIView *)appTitle_1, 0, 30, screen_w, 40);
UILabel *appSub_1 = UILabel_create((UIView *)_v0);
UILabel_set_text(appSub_1, "Local session");
UILabel_set_color((UILabel *)appSub_1, 0x6E7781);
UILabel_set_font((UILabel *)appSub_1, &lv_font_montserrat_14);
UILabel_set_alignment((UILabel *)appSub_1, 1);
UIView_set_frame((UIView *)appSub_1, 0, 66, screen_w, 22);
UIView *terminal_card = UIView_create((UIView *)_v0);
UIView_set_background_color((UIView *)terminal_card, 0x0E0E11);
lv_obj_set_style_pad_all(UIView_native((UIView *)terminal_card), 18, 0);
UIView_set_corner_radius((UIView *)terminal_card, 20);
UIView_set_frame((UIView *)terminal_card, 20, 120, 353, 240);
UILabel *_v3 = UILabel_create((UIView *)terminal_card);
UILabel_set_text(_v3, "$ ssh device@192.168.1.24");
UILabel_set_color((UILabel *)_v3, 0xC7C7CE);
UILabel_set_font((UILabel *)_v3, &lv_font_montserrat_14);
UIView_set_frame((UIView *)_v3, 0, 0, 317, 0);
UILabel *_v4 = UILabel_create((UIView *)terminal_card);
UILabel_set_text(_v4, "Connected to factory device");
UILabel_set_color((UILabel *)_v4, 0x64D47F);
UILabel_set_font((UILabel *)_v4, &lv_font_montserrat_14);
UIView_set_frame((UIView *)_v4, 0, 28, 317, 0);
UILabel *_v5 = UILabel_create((UIView *)terminal_card);
UILabel_set_text(_v5, "firmware  v2.4.18");
UILabel_set_color((UILabel *)_v5, 0xC7C7CE);
UILabel_set_font((UILabel *)_v5, &lv_font_montserrat_14);
UIView_set_frame((UIView *)_v5, 0, 56, 317, 0);
UILabel *_v6 = UILabel_create((UIView *)terminal_card);
UILabel_set_text(_v6, "wifi      192.168.1.24");
UILabel_set_color((UILabel *)_v6, 0xC7C7CE);
UILabel_set_font((UILabel *)_v6, &lv_font_montserrat_14);
UIView_set_frame((UIView *)_v6, 0, 82, 317, 0);
UILabel *_v7 = UILabel_create((UIView *)terminal_card);
UILabel_set_text(_v7, "battery   87%");
UILabel_set_color((UILabel *)_v7, 0xC7C7CE);
UILabel_set_font((UILabel *)_v7, &lv_font_montserrat_14);
UIView_set_frame((UIView *)_v7, 0, 108, 317, 0);
UILabel *cursor = UILabel_create((UIView *)terminal_card);
UILabel_set_text(cursor, "▌");
UILabel_set_color((UILabel *)cursor, 0x5AC8FA);
UILabel_set_font((UILabel *)cursor, &lv_font_montserrat_14);
UIView_set_frame((UIView *)cursor, 0, 150, screen_w - 0, 0);
UILabel *_v9 = UILabel_create((UIView *)_v0);
UILabel_set_text(_v9, "Quick Actions");
UILabel_set_color((UILabel *)_v9, 0x141418);
UILabel_set_font((UILabel *)_v9, &lv_font_montserrat_20);
UIView_set_frame((UIView *)_v9, 20, 390, screen_w - 20, 0);
UIView *actConnect = UIView_create((UIView *)_v0);
UIView_set_background_color((UIView *)actConnect, 0xFFFFFF);
UIView_set_corner_radius((UIView *)actConnect, 12);
UIView_set_user_interaction((UIView *)actConnect, true);
UIView_set_frame((UIView *)actConnect, 20, 430, 120, 92);
UILabel *aicon_10 = UILabel_create((UIView *)actConnect);
UILabel_set_text(aicon_10, LV_SYMBOL_USB);
UILabel_set_color((UILabel *)aicon_10, 0x2F81F7);
UILabel_set_font((UILabel *)aicon_10, &lv_font_montserrat_28);
UILabel_set_alignment((UILabel *)aicon_10, 1);
UIView_set_frame((UIView *)aicon_10, 0, 12, 120, 36);
UILabel *atitle_10 = UILabel_create((UIView *)actConnect);
UILabel_set_text(atitle_10, "Connect");
UILabel_set_color((UILabel *)atitle_10, 0x141418);
UILabel_set_font((UILabel *)atitle_10, &lv_font_montserrat_16);
UILabel_set_alignment((UILabel *)atitle_10, 1);
UIView_set_frame((UIView *)atitle_10, 0, 54, 120, 24);
UIView *actScan = UIView_create((UIView *)_v0);
UIView_set_background_color((UIView *)actScan, 0xFFFFFF);
UIView_set_corner_radius((UIView *)actScan, 12);
UIView_set_user_interaction((UIView *)actScan, true);
UIView_set_frame((UIView *)actScan, 140, 430, 120, 92);
UILabel *aicon_11 = UILabel_create((UIView *)actScan);
UILabel_set_text(aicon_11, LV_SYMBOL_LOOP);
UILabel_set_color((UILabel *)aicon_11, 0x2F81F7);
UILabel_set_font((UILabel *)aicon_11, &lv_font_montserrat_28);
UILabel_set_alignment((UILabel *)aicon_11, 1);
UIView_set_frame((UIView *)aicon_11, 0, 12, 120, 36);
UILabel *atitle_11 = UILabel_create((UIView *)actScan);
UILabel_set_text(atitle_11, "Scan");
UILabel_set_color((UILabel *)atitle_11, 0x141418);
UILabel_set_font((UILabel *)atitle_11, &lv_font_montserrat_16);
UILabel_set_alignment((UILabel *)atitle_11, 1);
UIView_set_frame((UIView *)atitle_11, 0, 54, 120, 24);
UIView *actReboot = UIView_create((UIView *)_v0);
UIView_set_background_color((UIView *)actReboot, 0xFFFFFF);
UIView_set_corner_radius((UIView *)actReboot, 12);
UIView_set_user_interaction((UIView *)actReboot, true);
UIView_set_frame((UIView *)actReboot, 260, 430, 120, 92);
UILabel *aicon_12 = UILabel_create((UIView *)actReboot);
UILabel_set_text(aicon_12, LV_SYMBOL_REFRESH);
UILabel_set_color((UILabel *)aicon_12, 0x2F81F7);
UILabel_set_font((UILabel *)aicon_12, &lv_font_montserrat_28);
UILabel_set_alignment((UILabel *)aicon_12, 1);
UIView_set_frame((UIView *)aicon_12, 0, 12, 120, 36);
UILabel *atitle_12 = UILabel_create((UIView *)actReboot);
UILabel_set_text(atitle_12, "Reboot");
UILabel_set_color((UILabel *)atitle_12, 0x141418);
UILabel_set_font((UILabel *)atitle_12, &lv_font_montserrat_16);
UILabel_set_alignment((UILabel *)atitle_12, 1);
UIView_set_frame((UIView *)atitle_12, 0, 54, 120, 24);
UILabel *_v13 = UILabel_create((UIView *)_v0);
UILabel_set_text(_v13, "Recent Sessions");
UILabel_set_color((UILabel *)_v13, 0x141418);
UILabel_set_font((UILabel *)_v13, &lv_font_montserrat_20);
UIView_set_frame((UIView *)_v13, 20, 545, screen_w - 20, 0);
UIView *factory_glass__24 = UIView_create((UIView *)_v0);
UIView_set_background_color((UIView *)factory_glass__24, 0xFFFFFF);
UIView_set_corner_radius((UIView *)factory_glass__24, 16);
UIView_set_user_interaction((UIView *)factory_glass__24, true);
UIView_set_frame((UIView *)factory_glass__24, 20, 580, 353, 70);
UILabel *dname_14 = UILabel_create((UIView *)factory_glass__24);
UILabel_set_text(dname_14, "Factory Glass #24");
UILabel_set_color((UILabel *)dname_14, 0x141418);
UILabel_set_font((UILabel *)dname_14, &lv_font_montserrat_16);
UIView_set_frame((UIView *)dname_14, 20, 14, 313, 24);
UILabel *dconn_14 = UILabel_create((UIView *)factory_glass__24);
UILabel_set_text(dconn_14, "Connected · 2 min ago");
UILabel_set_color((UILabel *)dconn_14, 0x2EAA59);
UILabel_set_font((UILabel *)dconn_14, &lv_font_montserrat_14);
UIView_set_frame((UIView *)dconn_14, 20, 42, 313, 20);
UIView *debug_board__07 = UIView_create((UIView *)_v0);
UIView_set_background_color((UIView *)debug_board__07, 0xFFFFFF);
UIView_set_corner_radius((UIView *)debug_board__07, 16);
UIView_set_user_interaction((UIView *)debug_board__07, true);
UIView_set_frame((UIView *)debug_board__07, 20, 665, 353, 70);
UILabel *dname_15 = UILabel_create((UIView *)debug_board__07);
UILabel_set_text(dname_15, "Debug Board #07");
UILabel_set_color((UILabel *)dname_15, 0x141418);
UILabel_set_font((UILabel *)dname_15, &lv_font_montserrat_16);
UIView_set_frame((UIView *)dname_15, 20, 14, 313, 24);
UILabel *dconn_15 = UILabel_create((UIView *)debug_board__07);
UILabel_set_text(dconn_15, "Disconnected · 1 hr ago");
UILabel_set_color((UILabel *)dconn_15, 0x8B8E97);
UILabel_set_font((UILabel *)dconn_15, &lv_font_montserrat_14);
UIView_set_frame((UIView *)dconn_15, 20, 42, 313, 20);
UIView *tabbar = UIView_create((UIView *)_v0);
UIView_set_background_color((UIView *)tabbar, 0xFFFFFF);
UIView_set_frame((UIView *)tabbar, 0, screen_h - 60, screen_w, 60);
UIButton *tab_terminal = UIButton_create((UIView *)tabbar);
UIButton_set_text(tab_terminal, "Terminal");
UIButton_set_title_color((UIButton *)tab_terminal, 0x2F81F7);
lv_obj_set_style_bg_opa(UIView_native((UIView *)tab_terminal), LV_OPA_TRANSP, 0);
UIView_set_frame((UIView *)tab_terminal, 0, 0, 160, 60);
UIButton *tab_devices = UIButton_create((UIView *)tabbar);
UIButton_set_text(tab_devices, "Devices");
UIButton_set_title_color((UIButton *)tab_devices, 0x8B8E97);
lv_obj_set_style_bg_opa(UIView_native((UIView *)tab_devices), LV_OPA_TRANSP, 0);
UIView_set_frame((UIView *)tab_devices, 160, 0, 160, 60);
UIButton *tab_settings = UIButton_create((UIView *)tabbar);
UIButton_set_text(tab_settings, "Settings");
UIButton_set_title_color((UIButton *)tab_settings, 0x8B8E97);
lv_obj_set_style_bg_opa(UIView_native((UIView *)tab_settings), LV_OPA_TRANSP, 0);
UIView_set_frame((UIView *)tab_settings, 320, 0, 160, 60);

    ids->back = back;
    ids->terminal_card = terminal_card;
    ids->cursor = cursor;
    ids->actConnect = actConnect;
    ids->actScan = actScan;
    ids->actReboot = actReboot;
    ids->factory_glass__24 = factory_glass__24;
    ids->debug_board__07 = debug_board__07;
    ids->tab_terminal = tab_terminal;
    ids->tab_devices = tab_devices;
    ids->tab_settings = tab_settings;
    return page;
}
