
#include <string.h>
#include "settings_xml.h"

UIView *settings_xml_build(SettingsXmlIds *ids)
{
    if (ids) memset(ids, 0, sizeof(*ids));
    const int32_t screen_w = lv_disp_get_hor_res(NULL);
    const int32_t screen_h = lv_disp_get_ver_res(NULL);

    UIView *page = UIView_create(NULL);
    UIView_set_background_color(page, 0x0B1220);
    UIView_set_frame(page, 0, 0, screen_w, screen_h);
UIView *_v0 = UIView_create((UIView *)page);
UIView_set_background_color((UIView *)_v0, 0xF7F7FA);
UIView_set_frame((UIView *)_v0, 0, 0, (screen_w) * 100 / 100, (screen_h) * 100 / 100);
UIButton *back = UIButton_create((UIView *)_v0);
UIButton_set_text(back, LV_SYMBOL_LEFT " Back");
UIButton_set_title_color((UIButton *)back, 0x1F2328);
UIView_set_background_color((UIView *)back, 0xE9EBEF);
lv_obj_set_style_bg_color(UIView_native((UIView *)back), lv_color_hex(0xD3D7DD), LV_PART_MAIN | LV_STATE_PRESSED);
UIView_set_corner_radius((UIView *)back, 16);
UIView_set_frame((UIView *)back, 20, 56, 130, 44);
UILabel *appTitle_1 = UILabel_create((UIView *)_v0);
UILabel_set_text(appTitle_1, "Settings");
UILabel_set_color((UILabel *)appTitle_1, 0x1F2328);
UILabel_set_font((UILabel *)appTitle_1, &lv_font_montserrat_28);
UILabel_set_alignment((UILabel *)appTitle_1, 1);
UIView_set_frame((UIView *)appTitle_1, 0, 30, screen_w, 40);
UILabel *appSub_1 = UILabel_create((UIView *)_v0);
UILabel_set_text(appSub_1, "Terminal preferences");
UILabel_set_color((UILabel *)appSub_1, 0x6E7781);
UILabel_set_font((UILabel *)appSub_1, &lv_font_montserrat_14);
UILabel_set_alignment((UILabel *)appSub_1, 1);
UIView_set_frame((UIView *)appSub_1, 0, 66, screen_w, 22);
UILabel *hdr_2 = UILabel_create((UIView *)_v0);
UILabel_set_text(hdr_2, "APPEARANCE");
UILabel_set_color((UILabel *)hdr_2, 0x57606A);
UILabel_set_font((UILabel *)hdr_2, &lv_font_montserrat_14);
UIView_set_frame((UIView *)hdr_2, 20, 120, screen_w - 40, 22);
UILabel *val_3 = UILabel_create((UIView *)_v0);
UILabel_set_text(val_3, "System");
UILabel_set_color((UILabel *)val_3, 0x6E7781);
UILabel_set_font((UILabel *)val_3, &lv_font_montserrat_16);
UILabel_set_alignment((UILabel *)val_3, 2);
UIView_set_frame((UIView *)val_3, screen_w - 168, 150 + 4, 144, 36);
UILabel *itTitle_3 = UILabel_create((UIView *)_v0);
UILabel_set_text(itTitle_3, "Theme");
UILabel_set_color((UILabel *)itTitle_3, 0x24292F);
UILabel_set_font((UILabel *)itTitle_3, &lv_font_montserrat_16);
UIView_set_frame((UIView *)itTitle_3, 24, 150, screen_w - 200, 40);
UILabel *val_4 = UILabel_create((UIView *)_v0);
UILabel_set_text(val_4, "Blue");
UILabel_set_color((UILabel *)val_4, 0x6E7781);
UILabel_set_font((UILabel *)val_4, &lv_font_montserrat_16);
UILabel_set_alignment((UILabel *)val_4, 2);
UIView_set_frame((UIView *)val_4, screen_w - 168, 202 + 4, 144, 36);
UILabel *itTitle_4 = UILabel_create((UIView *)_v0);
UILabel_set_text(itTitle_4, "Accent Color");
UILabel_set_color((UILabel *)itTitle_4, 0x24292F);
UILabel_set_font((UILabel *)itTitle_4, &lv_font_montserrat_16);
UIView_set_frame((UIView *)itTitle_4, 24, 202, screen_w - 200, 40);
UILabel *val_5 = UILabel_create((UIView *)_v0);
UILabel_set_text(val_5, "14 pt");
UILabel_set_color((UILabel *)val_5, 0x6E7781);
UILabel_set_font((UILabel *)val_5, &lv_font_montserrat_16);
UILabel_set_alignment((UILabel *)val_5, 2);
UIView_set_frame((UIView *)val_5, screen_w - 168, 254 + 4, 144, 36);
UILabel *itTitle_5 = UILabel_create((UIView *)_v0);
UILabel_set_text(itTitle_5, "Font Size");
UILabel_set_color((UILabel *)itTitle_5, 0x24292F);
UILabel_set_font((UILabel *)itTitle_5, &lv_font_montserrat_16);
UIView_set_frame((UIView *)itTitle_5, 24, 254, screen_w - 200, 40);
UILabel *val_6 = UILabel_create((UIView *)_v0);
UILabel_set_text(val_6, "JetBrains Mono");
UILabel_set_color((UILabel *)val_6, 0x6E7781);
UILabel_set_font((UILabel *)val_6, &lv_font_montserrat_16);
UILabel_set_alignment((UILabel *)val_6, 2);
UIView_set_frame((UIView *)val_6, screen_w - 168, 306 + 4, 144, 36);
UILabel *itTitle_6 = UILabel_create((UIView *)_v0);
UILabel_set_text(itTitle_6, "Terminal Font");
UILabel_set_color((UILabel *)itTitle_6, 0x24292F);
UILabel_set_font((UILabel *)itTitle_6, &lv_font_montserrat_16);
UIView_set_frame((UIView *)itTitle_6, 24, 306, screen_w - 200, 40);
UILabel *hdr_7 = UILabel_create((UIView *)_v0);
UILabel_set_text(hdr_7, "BEHAVIOR");
UILabel_set_color((UILabel *)hdr_7, 0x57606A);
UILabel_set_font((UILabel *)hdr_7, &lv_font_montserrat_14);
UIView_set_frame((UIView *)hdr_7, 20, 380, screen_w - 40, 22);
UISwitch *confirm_destructive_commands = UISwitch_create((UIView *)_v0);
UISwitch_set_on_color((UISwitch *)confirm_destructive_commands, 0x2F81F7);
UIView_set_frame((UIView *)confirm_destructive_commands, screen_w - 104, 410 + 4, 80, 32);
UILabel *itTitle_8 = UILabel_create((UIView *)_v0);
UILabel_set_text(itTitle_8, "Confirm Destructive Commands");
UILabel_set_color((UILabel *)itTitle_8, 0x24292F);
UILabel_set_font((UILabel *)itTitle_8, &lv_font_montserrat_16);
UIView_set_frame((UIView *)itTitle_8, 24, 410, screen_w - 200, 40);
UISwitch *auto_reconnect = UISwitch_create((UIView *)_v0);
UISwitch_set_on_color((UISwitch *)auto_reconnect, 0x2F81F7);
UIView_set_frame((UIView *)auto_reconnect, screen_w - 104, 462 + 4, 80, 32);
UILabel *itTitle_9 = UILabel_create((UIView *)_v0);
UILabel_set_text(itTitle_9, "Auto Reconnect");
UILabel_set_color((UILabel *)itTitle_9, 0x24292F);
UILabel_set_font((UILabel *)itTitle_9, &lv_font_montserrat_16);
UIView_set_frame((UIView *)itTitle_9, 24, 462, screen_w - 200, 40);
UISwitch *keep_screen_awake = UISwitch_create((UIView *)_v0);
UISwitch_set_on_color((UISwitch *)keep_screen_awake, 0x2F81F7);
UIView_set_frame((UIView *)keep_screen_awake, screen_w - 104, 514 + 4, 80, 32);
UILabel *itTitle_10 = UILabel_create((UIView *)_v0);
UILabel_set_text(itTitle_10, "Keep Screen Awake");
UILabel_set_color((UILabel *)itTitle_10, 0x24292F);
UILabel_set_font((UILabel *)itTitle_10, &lv_font_montserrat_16);
UIView_set_frame((UIView *)itTitle_10, 24, 514, screen_w - 200, 40);
UILabel *hdr_11 = UILabel_create((UIView *)_v0);
UILabel_set_text(hdr_11, "CONNECTION");
UILabel_set_color((UILabel *)hdr_11, 0x57606A);
UILabel_set_font((UILabel *)hdr_11, &lv_font_montserrat_14);
UIView_set_frame((UIView *)hdr_11, 20, 588, screen_w - 40, 22);
UILabel *val_12 = UILabel_create((UIView *)_v0);
UILabel_set_text(val_12, "Wi-Fi");
UILabel_set_color((UILabel *)val_12, 0x6E7781);
UILabel_set_font((UILabel *)val_12, &lv_font_montserrat_16);
UILabel_set_alignment((UILabel *)val_12, 2);
UIView_set_frame((UIView *)val_12, screen_w - 168, 618 + 4, 144, 36);
UILabel *itTitle_12 = UILabel_create((UIView *)_v0);
UILabel_set_text(itTitle_12, "Default Transport");
UILabel_set_color((UILabel *)itTitle_12, 0x24292F);
UILabel_set_font((UILabel *)itTitle_12, &lv_font_montserrat_16);
UIView_set_frame((UIView *)itTitle_12, 24, 618, screen_w - 200, 40);
UILabel *val_13 = UILabel_create((UIView *)_v0);
UILabel_set_text(val_13, "5 sec");
UILabel_set_color((UILabel *)val_13, 0x6E7781);
UILabel_set_font((UILabel *)val_13, &lv_font_montserrat_16);
UILabel_set_alignment((UILabel *)val_13, 2);
UIView_set_frame((UIView *)val_13, screen_w - 168, 670 + 4, 144, 36);
UILabel *itTitle_13 = UILabel_create((UIView *)_v0);
UILabel_set_text(itTitle_13, "Connection Timeout");
UILabel_set_color((UILabel *)itTitle_13, 0x24292F);
UILabel_set_font((UILabel *)itTitle_13, &lv_font_montserrat_16);
UIView_set_frame((UIView *)itTitle_13, 24, 670, screen_w - 200, 40);

    ids->back = back;
    ids->confirm_destructive_commands = confirm_destructive_commands;
    ids->auto_reconnect = auto_reconnect;
    ids->keep_screen_awake = keep_screen_awake;
    return page;
}
